### ISSUE TITLE
Linking of activities withing the app

### ISSUE THREAD

**Issue by JIBIN-P** [ENGG-4/Traffic-Violators-1.0#1]
The starting link has been made but facing some difficulties with the inner activities. 
f34a360e8aa073e10db6b11472c86a3480ada9a6 - Merged all the necessary authentication procedures

**Comment by JIBIN-P** [comment]
The activity fixing with regards to firebase operations is fixed, but can't set the main screen as MainActivity else it will again have the same problem.
5810972a9fa6345bf2c9bc2e3d9a700738d5afa9 - commit hash for the temporary fix.

**Comment by i1-D** [comment]
Fixed the issue by adding splash screen
